/* This file is part of STonX, the Atari ST Emulator for Unix/X
 * ============================================================
 * STonX is free software and comes with NO WARRANTY - read the file
 * COPYING for details
 */
#ifndef IOFUNCS_H
#define IOFUNCS_H

#include "defs.h"

extern B LOAD_B_fffa01(void);
extern B LOAD_B_fffa03(void);
extern B LOAD_B_fffa05(void);
extern B LOAD_B_fffa07(void);
extern B LOAD_B_fffa09(void);
extern B LOAD_B_fffa0b(void);
extern B LOAD_B_fffa0d(void);
extern B LOAD_B_fffa0f(void);
extern B LOAD_B_fffa11(void);
extern B LOAD_B_fffa13(void);
extern B LOAD_B_fffa15(void);
extern B LOAD_B_fffa17(void);
extern B LOAD_B_fffa19(void);
extern B LOAD_B_fffa1b(void);
extern B LOAD_B_fffa1d(void);
extern B LOAD_B_fffa1f(void);
extern B LOAD_B_fffa21(void);
extern B LOAD_B_fffa23(void);
extern B LOAD_B_fffa25(void);
extern B LOAD_B_fffa27(void);
extern B LOAD_B_fffa29(void);
extern B LOAD_B_fffa2b(void);
extern B LOAD_B_fffa2d(void);
extern B LOAD_B_fffa2f(void);
extern B LOAD_B_fffa31(void);
extern B LOAD_B_fffc00(void);
extern B LOAD_B_fffc02(void);
extern B LOAD_B_fffc04(void);
extern B LOAD_B_fffc06(void);
extern B LOAD_B_fffc20(void);
extern B LOAD_B_fffc21(void);
extern B LOAD_B_fffc22(void);
extern B LOAD_B_fffc23(void);
extern B LOAD_B_fffc24(void);
extern B LOAD_B_fffc25(void);
extern B LOAD_B_fffc26(void);
extern B LOAD_B_fffc27(void);
extern B LOAD_B_fffc28(void);
extern B LOAD_B_fffc29(void);
extern B LOAD_B_fffc2a(void);
extern B LOAD_B_fffc2b(void);
extern B LOAD_B_fffc2c(void);
extern B LOAD_B_fffc2d(void);
extern B LOAD_B_fffc2e(void);
extern B LOAD_B_fffc2f(void);
extern B LOAD_B_fffc30(void);
extern B LOAD_B_fffc31(void);
extern B LOAD_B_fffc32(void);
extern B LOAD_B_fffc33(void);
extern B LOAD_B_fffc34(void);
extern B LOAD_B_fffc35(void);
extern B LOAD_B_fffc36(void);
extern B LOAD_B_fffc37(void);
extern B LOAD_B_fffc38(void);
extern B LOAD_B_fffc39(void);
extern B LOAD_B_fffc3a(void);
extern B LOAD_B_fffc3b(void);
extern B LOAD_B_fffc3c(void);
extern B LOAD_B_fffc3d(void);
extern B LOAD_B_fffc3e(void);
extern B LOAD_B_fffc3f(void);
extern void STORE_B_fffa01(B v);
extern void STORE_B_fffa03(B v);
extern void STORE_B_fffa05(B v);
extern void STORE_B_fffa07(B v);
extern void STORE_B_fffa09(B v);
extern void STORE_B_fffa0b(B v);
extern void STORE_B_fffa0d(B v);
extern void STORE_B_fffa0f(B v);
extern void STORE_B_fffa11(B v);
extern void STORE_B_fffa13(B v);
extern void STORE_B_fffa15(B v);
extern void STORE_B_fffa17(B v);
extern void STORE_B_fffa19(B v);
extern void STORE_B_fffa1b(B v);
extern void STORE_B_fffa1d(B v);
extern void STORE_B_fffa1f(B v);
extern void STORE_B_fffa21(B v);
extern void STORE_B_fffa23(B v);
extern void STORE_B_fffa25(B v);
extern void STORE_B_fffa27(B v);
extern void STORE_B_fffa29(B v);
extern void STORE_B_fffa2b(B v);
extern void STORE_B_fffa2d(B v);
extern void STORE_B_fffa2f(B v);
extern void STORE_B_fffa31(B v);
extern void STORE_B_fffc00(B v);
extern void STORE_B_fffc02(B v);
extern void STORE_B_fffc04(B v);
extern void STORE_B_fffc06(B v);
extern void STORE_B_fffc20(B v);
extern void STORE_B_fffc21(B v);
extern void STORE_B_fffc22(B v);
extern void STORE_B_fffc23(B v);
extern void STORE_B_fffc24(B v);
extern void STORE_B_fffc25(B v);
extern void STORE_B_fffc26(B v);
extern void STORE_B_fffc27(B v);
extern void STORE_B_fffc28(B v);
extern void STORE_B_fffc29(B v);
extern void STORE_B_fffc2a(B v);
extern void STORE_B_fffc2b(B v);
extern void STORE_B_fffc2c(B v);
extern void STORE_B_fffc2d(B v);
extern void STORE_B_fffc2e(B v);
extern void STORE_B_fffc2f(B v);
extern void STORE_B_fffc30(B v);
extern void STORE_B_fffc31(B v);
extern void STORE_B_fffc32(B v);
extern void STORE_B_fffc33(B v);
extern void STORE_B_fffc34(B v);
extern void STORE_B_fffc35(B v);
extern void STORE_B_fffc36(B v);
extern void STORE_B_fffc37(B v);
extern void STORE_B_fffc38(B v);
extern void STORE_B_fffc39(B v);
extern void STORE_B_fffc3a(B v);
extern void STORE_B_fffc3b(B v);
extern void STORE_B_fffc3c(B v);
extern void STORE_B_fffc3d(B v);
extern void STORE_B_fffc3e(B v);
extern void STORE_B_fffc3f(B v);
extern B LOAD_B_ff8200(void);
extern B LOAD_B_ff8202(void);
extern B LOAD_B_ff8205(void);
extern B LOAD_B_ff8207(void);
extern B LOAD_B_ff8209(void);
extern B LOAD_B_ff8604(void);
extern B LOAD_B_ff8605(void);
extern B LOAD_B_ff8606(void);
extern B LOAD_B_ff8607(void);
extern B LOAD_B_ff8800(void);
extern B LOAD_B_ff8801(void);
extern B LOAD_B_ff8802(void);
extern B LOAD_B_ff8803(void);
extern B LOAD_B_ff8920(void);
extern B LOAD_B_ff8921(void);
extern B LOAD_B_ff8922(void);
extern B LOAD_B_ff8923(void);
extern B LOAD_B_ff8924(void);
extern B LOAD_B_ff8925(void);
extern B LOAD_B_ff8a28(void);
extern B LOAD_B_ff8a29(void);
extern B LOAD_B_ff8a2a(void);
extern B LOAD_B_ff8a2b(void);
extern B LOAD_B_ff8a2c(void);
extern B LOAD_B_ff8a2d(void);
extern B LOAD_B_ff8a32(void);
extern B LOAD_B_ff8a33(void);
extern B LOAD_B_ff8a34(void);
extern B LOAD_B_ff8a35(void);
extern B LOAD_B_ff8a36(void);
extern B LOAD_B_ff8a37(void);
extern B LOAD_B_ff8a38(void);
extern B LOAD_B_ff8a39(void);
extern B LOAD_B_ff8a3a(void);
extern B LOAD_B_ff8a3b(void);
extern B LOAD_B_ff8a3c(void);
extern B LOAD_B_ff8a3d(void);
extern void STORE_B_ff7f30(B v);
extern void STORE_B_ff7f31(B v);
extern void STORE_B_ff8200(B v);
extern void STORE_B_ff8201(B v);
extern void STORE_B_ff8202(B v);
extern void STORE_B_ff8203(B v);
extern void STORE_B_ff820a(B v);
extern void STORE_B_ff820d(B v);
extern void STORE_B_ff8260(B v);
extern void STORE_B_ff8261(B v);
extern void STORE_B_ff8262(B v);
extern void STORE_B_ff8263(B v);
extern void STORE_B_ff8604(B v);
extern void STORE_B_ff8605(B v);
extern void STORE_B_ff8606(B v);
extern void STORE_B_ff8607(B v);
extern void STORE_B_ff8800(B v);
extern void STORE_B_ff8801(B v);
extern void STORE_B_ff8802(B v);
extern void STORE_B_ff8803(B v);
extern void STORE_B_ff8a28(B v);
extern void STORE_B_ff8a29(B v);
extern void STORE_B_ff8a2a(B v);
extern void STORE_B_ff8a2b(B v);
extern void STORE_B_ff8a2c(B v);
extern void STORE_B_ff8a2d(B v);
extern void STORE_B_ff8a32(B v);
extern void STORE_B_ff8a33(B v);
extern void STORE_B_ff8a34(B v);
extern void STORE_B_ff8a35(B v);
extern void STORE_B_ff8a36(B v);
extern void STORE_B_ff8a37(B v);
extern void STORE_B_ff8a38(B v);
extern void STORE_B_ff8a39(B v);
extern void STORE_B_ff8a3a(B v);
extern void STORE_B_ff8a3b(B v);
extern void STORE_B_ff8a3c(B v);
extern void STORE_B_ff8a3d(B v);
#endif /* IOFUNCS_H */
