# This is a dummy Makefile for the mint/ folder of STonX.
# The files in this directory are actually compiled from the main Makefile
# in the main folder... but feel free to include here a more flexible
# automake/autoconf solution, too!

# BTW: If you're having trouble compiling this MiNT-stuff on a non-Linux
# platform, try to switch off all MiNT related options in options.h !

all:
	@echo "The MiNT related files will be compiled from the main Makefile!"
